<?php include BASE_DIR . 'templates' . DS . 'includes' . DS . 'nav.phtml'?>

<div class="container" id="main-content">
    <h2>Welcome!</h2>
    <p>This website is made as a requirement of interview task of Peopleplan</p>

    <p>
      The task consists of three parts.
      <ol>
        <li>Read from CSV and insert data to MySQL through command line PHP</li>
        <li>Check if given string is palindrome</li>
        <li>Retrieve second highest salary from given data set</li>
      </ol>
    </p>
  </div>
