<div class="space-bottom space-top">
    <a href="<?php echo BASE_URL; ?>app/index.php" class="btn btn-primary">Home Page</a>
    <a href="<?php echo BASE_URL; ?>app/read_csv.php" class="btn btn-primary">Read CSV</a>
    <a href="<?php echo BASE_URL; ?>app/palindrome.php" class="btn btn-primary">Palindrome</a>
    <a href="<?php echo BASE_URL; ?>app/second_highest.php" class="btn btn-primary">Second Highest</a>
</div>
