<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $page_title; ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <style>
        .space-top { margin-top: 20px;}
        .space-bottom { margin-bottom: 20px;}
    </style>
</head>
<body>
    <div class="container">
        <div class="jumbotron text-center">
                <h1>PeoplePlan Task</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php if ($error != ""): ?>
                    <div class="alert alert-danger">
                        <?php echo $error; ?>
                    </div>
                <?php endif; ?>
                <?php if ($success != ""): ?>
                    <div class="alert alert-success">
                        <?php echo $success; ?>
                    </div>
                <?php endif; ?>
                <?php if ($errors != ""): ?>
                    <div class="alert alert-danger">
                        <ul>
                            <?php foreach($errors as $key => $value): ?>
                                <li><?php echo $errors[$key][0]; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
                <?php echo $content; ?>
            </div>
        </div>
    </div> <!--container close -->
</body>
</html>
